messaging:
  exchange: team-finder-exchange
  accept-cap:
    binding: accept-cap
    queue: accept-cap-queue
  decline-cap:
    binding: decline-cap
    queue: decline-cap-queue
  check-cap-request:
    binding: check-cap-req
    queue: check-cap-request
  check-cap-result:
    binding: check-cap-res
    queue: check-cap-result

spring:

  rabbitmq:

    host: localhost
    port: 5672
    username: tf-user
    password: tf-pass


  data:

    mongodb:

      host: localhost
      port: 27017
      database: team-db
      username: team-db-user
      password: team-db-pass

  cloud:

    consul:

      host: localhost
      port: 8500

      config:

        enabled: true
        prefix: config

      discovery:

        register: true

    service-registry:

        auto-registration:

          enabled: true

server:
  port: 8080
